"""create the initial tables

Revision ID: 86f966c0dc4a
Revises: 
Create Date: 2026-09-27 16:19:34.964380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86f966c0dc4a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('installations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_installation_id', sa.BigInteger(), nullable=False),
    sa.Column('account_login', sa.String(length=255), nullable=False),
    sa.Column('installed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_installation_id')
    )
    op.create_table('repos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('installation_id', sa.Integer(), nullable=False),
    sa.Column('github_repo_id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(length=512), nullable=False),
    sa.Column('default_branch', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['installation_id'], ['installations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_repo_id')
    )
    op.create_index(op.f('ix_repos_installation_id'), 'repos', ['installation_id'], unique=False)
    op.create_table('repo_suppressions',
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('suppressed', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('repo_id', 'category')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('head_sha', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('context_status', sa.String(length=16), nullable=True),
    sa.Column('github_review_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("context_status IS NULL OR context_status IN ('ok', 'degraded', 'unavailable')", name='ck_reviews_context_status'),
    sa.CheckConstraint("status IN ('received', 'processing', 'posting', 'posted', 'skipped', 'no_findings', 'superseded', 'failed')", name='ck_reviews_status'),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_id', 'pr_number', 'head_sha', name='uq_reviews_repo_pr_head')
    )
    op.create_index('ix_reviews_repo_created', 'reviews', ['repo_id', 'created_at'], unique=False)
    op.create_index('ix_reviews_status_updated', 'reviews', ['status', 'updated_at'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('file', sa.String(length=1024), nullable=False),
    sa.Column('line', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('posted', sa.Boolean(), nullable=False),
    sa.Column('github_comment_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_review_id'), 'findings', ['review_id'], unique=False)
    op.create_table('webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_id', sa.String(length=64), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=True),
    sa.Column('github_repo_id', sa.BigInteger(), nullable=True),
    sa.Column('pr_number', sa.Integer(), nullable=True),
    sa.Column('head_sha', sa.String(length=40), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("outcome IN ('accepted', 'duplicate', 'ignored')", name='ck_webhook_events_outcome'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('delivery_id')
    )
    op.create_table('outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_outcomes_repo_category', 'outcomes', ['repo_id', 'category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_outcomes_repo_category', table_name='outcomes')
    op.drop_table('outcomes')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_findings_review_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index('ix_reviews_status_updated', table_name='reviews')
    op.drop_index('ix_reviews_repo_created', table_name='reviews')
    op.drop_table('reviews')
    op.drop_table('repo_suppressions')
    op.drop_index(op.f('ix_repos_installation_id'), table_name='repos')
    op.drop_table('repos')
    op.drop_table('installations')
    # ### end Alembic commands ###
